sender_0 = "180701159311577569411644132017670017218"
sender_1 = "56241169990954142494367849715183460669"
recipient_0 = "280495749182989910196488438306836233797"
recipient_1 = "103057432069354398235191128206611333060"
mint_0 = "86391616295136460872833047503299145020"
mint_1 = "100776754505472238064130011414406808816"
amount = "10"
secret = "11"
nonce = "13"
auth_tag = "807663881355484719274654607164006998614"
